FROM mcr.microsoft.com/windows/servercore:ltsc2022
RUN powershell -Command \
    Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe && \
    Start-Process vs_buildtools.exe -ArgumentList '--quiet --wait --norestart --nocache \
    --add Microsoft.VisualStudio.Workload.VCTools \
    --add Microsoft.VisualStudio.Component.Windows11SDK.22621' -NoNewWindow -Wait && \
    del vs_buildtools.exe